name: C/C++ Premake5
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs: 
  build:
    env: 
      VCPKG_DEFAULT_TRIPLET: "x64-linux"
      
    runs-on: ubuntu-latest

    steps:
      # - working-directory: ./
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v7.6
        with: 
          vcpkgGitCommitId: c5da4ba
          runVcpkgInstall: true
          vcpkgJsonGlob: '**/vcpkg.json'
          
      - name: Download premake
        uses: BEASTSM96/premake-action@v1.3.1
      - name: Setup premake
        # You may pin to the exact commit or the version.
        # uses: abel0b/setup-premake@b80dc6f70e8ab159fb854bdadbeb1a53cfc28723
        uses: abel0b/setup-premake@v2.4
        with:
          # Premake version
          version: 5.0.0-beta2
      - name: Compile project
        run: premake5 gmake2 && make
          
